baseURL = 'https://danhill.us/'
languageCode = 'en-us'
title = 'danhill.us'
theme = 'term'
enableRobotsTXT = true
summaryLength = 24

[pagination]
pagerSize = 6

[taxonomies]
tag = 'tags'
category = 'categories'

[markup]
  [markup.highlight]
  noClasses = false
  lineNos = true
  [markup.tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false

[params]
description = 'Dan Hill on software, systems, and whatever else seems useful.'

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 10

[[menu.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30